services:
    _defaults:
        public: true

    swp_settings.manager.settings:
        class: SWP\Bundle\SettingsBundle\Manager\SettingsManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@SWP\Bundle\SettingsBundle\Provider\SettingsProviderChain'
            - '@swp.repository.settings'
            - '@swp.factory.settings'
            - '@swp_settings.context.scope'
    SWP\Bundle\SettingsBundle\Manager\SettingsManagerInterface: '@swp_settings.manager.settings'

    swp_settings.context.scope:
        class: SWP\Bundle\SettingsBundle\Context\ScopeContext
        public: true
    SWP\Bundle\SettingsBundle\Context\ScopeContextInterface: '@swp_settings.context.scope'

    SWP\Bundle\SettingsBundle\Provider\ConfigurationSettingsProvider:
        arguments:
            - '%swp_settings.settings%'

    SWP\Bundle\SettingsBundle\Provider\SettingsProviderChain:
        arguments:
            - ['@SWP\Bundle\SettingsBundle\Provider\ConfigurationSettingsProvider']
